# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Engin Kurutepe
job: mobile product consultant
email: engin@kurutepe.com
description: > 
  Engin Kurutepe. Mobile Product Consultant. iOS Developer. Based in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kurutepe.com" # the base hostname & protocol for your site
twitter_username: ekurutepe
github_username:  ekurutepe

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: engin
